### ISSUE TITLE
Fix the website (https://www.skycoin.net/markets/)

### ISSUE THREAD

**Issue by djhives** [skycoin/skycoin.net#178] opened 2017-12-25 16:29 UTC
Simplify the "BUY SKYCOIN" webpage (https://www.skycoin.net/markets/) to read:

**Buy Skycoin NOW in 3 easy steps:

1) Download Skycoin wallet and get address
2) Put your address in otc.skycoin.net
3) Send bitcoin to the address to receive your skycoin instantly**

- This should be at the VERY TOP of the page...
- Leave the rest of the page AS-IS
- * ALSO change the webpage to: https://www.skycoin.net/buy

Questions?
Email Lord hives at: rolledoats@hotmail.com

**Comment by skycoin-manager** [comment] 2018-01-01 05:07
1> Rename the markets page from "skycoin.net/markets" to "skycoin.net/buy" (done)

2> Change the header for OTC as "How to buy OTC at otc.skycoin.net"

**Comment by gz-c** [comment] 2018-01-28 05:23
duplicate of #184

**Closed by gz-c** 2018-01-28 05:23 UTC
